# Generated by Django 5.1.6 on 2025-02-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArticle', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('numRef', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demarapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idReport', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demarapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('orderItem', models.ManyToManyField(to='demarapp.article')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demarapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idCart', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('cartItem', models.ManyToManyField(to='demarapp.article')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demarapp.user')),
            ],
        ),
    ]
