# Generated by Django 5.1.7 on 2025-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='idArticle',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='idCategory',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
