# Generated by Django 5.1.7 on 2025-03-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0004_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
