# Generated by Django 5.1.7 on 2025-03-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0006_remove_cart_cartitem_alter_cart_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user',
        ),
    ]
