# Generated by Django 5.1.7 on 2025-04-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
