# Generated by Django 5.1.7 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0013_remove_order_orderitem_orderitem_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/articles/'),
        ),
    ]
