# Generated by Django 5.1.7 on 2025-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarapp', '0014_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
